# Default initial positions for m_0330939_001's ros2_control fake system

initial_positions:
  c_203_robot_arm_joint_1: 0
  c_203_robot_arm_joint_2: 0
  c_203_robot_arm_joint_3: 0
  c_203_robot_arm_joint_4: 0
  c_204_pick_place_system_joint_1: 0
  c_204_pick_place_system_joint_2: 0
  c_206_height_check_system_joint_1: 0
  c_206_height_check_system_joint_2: 0