# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    c_206_height_check_system_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    c_203_robot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    c_204_pick_place_system_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    c_208_workpiece_lifter_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    c_207_workpiece_feeder_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

c_206_height_check_system_controller:
  ros__parameters:
    joints:
      - c_206_height_check_system_joint_1
      - c_206_height_check_system_joint_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
c_203_robot_arm_controller:
  ros__parameters:
    joints:
      - c_203_robot_arm_joint_1
      - c_203_robot_arm_joint_2
      - c_203_robot_arm_joint_3
      - c_203_robot_arm_joint_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
c_204_pick_place_system_controller:
  ros__parameters:
    joints:
      - c_204_pick_place_system_joint_1
      - c_204_pick_place_system_joint_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
c_208_workpiece_lifter_controller:
  ros__parameters:
    joints:
      - c_208_workpiece_lifter_joint_1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
c_207_workpiece_feeder_controller:
  ros__parameters:
    joints:
      - c_207_workpiece_feeder_joint_1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity