# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - m_5326927_001_controller

  m_5326927_001_controller:
    type: FollowJointTrajectory
    joints:
      - m_5326927_001_joint_1