# MoveIt uses this configuration for controller management

controller_names:
  - m_2025643_001_controller

m_2025643_001_controller:
  action_ns: follow_joint_trajectory
  default: True
  type: FollowJointTrajectory
  joints:
    - m_2025643_001_joint_1
    - m_2025643_001_joint_2