# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  c_203_robot_arm_joint_1:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_203_robot_arm_joint_2:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_203_robot_arm_joint_3:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_203_robot_arm_joint_4:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_204_pick_place_system_joint_1:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_204_pick_place_system_joint_2:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_206_height_check_system_joint_1:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_206_height_check_system_joint_2:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0

  c_303_robot_arm_2_joint_1:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_303_robot_arm_2_joint_2:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_303_robot_arm_2_joint_3:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_303_robot_arm_2_joint_4:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_304_pick_place_system_2_joint_1:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_304_pick_place_system_2_joint_2:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_306_height_check_system_2_joint_1:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  c_306_height_check_system_2_joint_2:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0