# MoveIt uses this configuration for controller management

controller_names:
  - m_2063306_000_controller

m_2063306_000_controller:
  action_ns: follow_joint_trajectory
  default: True
  type: FollowJointTrajectory
  joints:
    - m_2063306_000_joint_1