# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    m_2063306_000_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

m_2063306_000_controller:
  ros__parameters:
    joints: 
      - m_2063306_000_joint_1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity